settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: BE Twitter Clone
  path: .
  commands:
    install:
      status: true
      method: go build -o tmp/app.out main.go
    run:
      status: true
      method: tmp/app.out
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
